# https://golangci-lint.run/docs/configuration/file/
version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
